
import React from 'react';
import './projects.css'
import stp from '../../img/stp.jpg'
import rgb from '../../img/rgb.jpg'
import corona from '../../img/corona.jpg'
import reciepe from '../../img/reciepe_maker.jpg'
import Button1 from '../../component/Button1'
import Button2 from '../../component/Button2'
import Footer from '../../component/footer'
import proj from '../../img/rocket.svg'



export default class Projects extends React.Component{
    render(){
        return(<>
                <title>Projects | Swarup Kumar</title> 
                <div className='projects'>
                    <div style={{display:"flex"}} className='head'>
                        <img style={{width:"100px",height:'100px'}} src={proj} />
                        <h1 style={{margin:"auto"}} className='top-heading'>Projects</h1>
                    </div>
                    <div className='projects-list'>
                        <div className='project stp'>
                            <img src={stp} alt='project stp'/>
                            <div className='desc'>
                                <h2>Stone Paper Scissor</h2>
                                <p>Bored? Computer is looking for a companion like you and challenging you if you can beat in this "no-description needed" Game. Try it out !!!</p>
                                <a href='https://eswarupkumar.github.io/Stone-Paper-Scissor/'target="_blank"><Button1/></a>
                                <a href='https://github.com/eswarupkumar/Stone-Paper-Scissor'target="_blank"><Button2/></a>
                            </div>
                        </div>
                        <div className='project rgb'>
                            <img src={rgb} alt='project rgb'/>
                            <div className='desc'>
                                <h2>RGB Color Game</h2>
                                <p>In this project/game, you have to choose the right color from the set of given color options based upon the random RGB value generated by the app. If your option is right then all the other colors will turn into the generated color. Fun, give it a shot!</p>
                                <a href='https://eswarupkumar.github.io/RGB_color_game/'target="_blank"><Button1/></a>
                                <a href='https://github.com/eswarupkumar/RGB_color_game'target="_blank"><Button2/></a>
                            </div>
                        </div>
                        <div className='project covid'>
                            <img src={corona} alt='project covid'/>
                            <div className='desc'>
                                <h2>Covid Patient Alert System</h2>
                                <p>An IoT based system on Node-Red dashboard on AWS EC2 Instance, in which recorded body temperature data of individuals stored in cloud is displayed in the dashboard with the help of time-date graph. When the body temperature of any individual goes up above 100 Fahrenheit ,other individuals receives mail to stay alert from being in contact.</p>
                                <a href='https://github.com/eswarupkumar/Covid-Patient-Alert-System'target="_blank"><Button2/></a>
                            </div>
                        </div>
                        <div className='project recipe'>
                            <img src={reciepe} alt='project reciepe'/>
                            <div className='desc'>
                                <h2>Reciepe Maker</h2>
                                <p>Worried about what to cook considering the ingredients in your refrigerator?

                                    You need to worry about it. Just you have to put effort into selecting the ingredients you have and based on that, it will show you what you can cook from the chosen ingredients. Interesting !!
                                    Considering the vastness of dishes list and mentioning each dish is quite tough. So few important yet mostly used dishes are taken into consideration for now.</p>
                                <a href='https://github.com/eswarupkumar'target="_blank"><Button1/></a>
                                <a href='https://github.com/eswarupkumar'target="_blank"><Button2/></a>
                            </div>
                            
                        </div>
                    </div>
                </div>
                <Footer/>
        </>)
    }
}